### ISSUE TITLE
error

### ISSUE THREAD

**Issue by conheaven** [JunnanDong/Localized-MiniGPT4#2]
Traceback (most recent call last):
  File "/home/khw/vlm/MiniGPT-4/demo_localized.py", line 107, in <module>
    llm_message = chat.answer(conv=chat_state,
  File "/home/khw/vlm/MiniGPT-4/minigpt4/conversation/conversation.py", line 186, in answer
    generation_dict = self.answer_prepare(conv, img_list, **kargs)
  File "/home/khw/vlm/MiniGPT-4/minigpt4/conversation/conversation.py", line 162, in answer_prepare
    embs = self.model.get_context_emb(prompt, img_list)
  File "/home/khw/vlm/MiniGPT-4/minigpt4/models/minigpt_base.py", line 69, in get_context_emb
    device = img_list[0].device
AttributeError: 'Image' object has no attribute 'device'

**Comment by conheaven** [comment]
change the code to this:

    for image_path in image_paths:
        # Load image
        from PIL import Image

        img = Image.open(image_path).convert('RGB')
        chat_state = CONV_VISION_Vicuna0.copy()
        img_list = []
        llm_message = chat.upload_img(img, chat_state, img_list)
        chat.encode_img(img_list)
        chat.ask(user_message, chat_state)
        llm_message = chat.answer(conv=chat_state,
                                  img_list=img_list,
                                  num_beams=1,
                                  temperature=1.0,
                                  max_new_tokens=300,
                                  max_length=2000)[0]
        logging.info('ImageID: ' + str(os.path.basename(image_path).split('.')))
        logging.info('MiniGPT4 Answer: ' + llm_message)
        logging.info('=================================')
   
   **_Add a line'chat.encode_img(img_list)'_**
